Sroll-VideoApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'ConsolaVideoApp'  # Agrega esta línea para establecer el namespace

urlpatterns = [
    path('', views.lista_videos_imagenes, name='lista_videos_imagenes'),
    path('cargar-elementos-scroll/', views.cargar_elementos_scroll, name='cargar_elementos_scroll'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Sroll-VideoApp/models.py
from django.db import models
from django.contrib.auth.models import User 
from PIL import Image
import os
from django.core.exceptions import ValidationError
from django.contrib import messages

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    

class Video(models.Model):
    titulo = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='imagenes_video/')
    sinopsis = models.TextField()
    enlace = models.FileField(upload_to='videos/')
    fecha_subida = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    categorias = models.ManyToManyField(Categoria, related_name='videos')
    visualizaciones = models.PositiveIntegerField(default=0)
    calificacion_promedio = models.FloatField(default=0.0)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='videos', default=1)
    

    def save(self, *args, **kwargs):
        # Primero guarda la imagen original
        super().save(*args, **kwargs)
        
        if self.imagen:
            try:
                img_path = self.imagen.path
                img = Image.open(img_path)

                if img.format not in ['JPEG', 'PNG', 'JPG', 'GIF']:
                    raise ValueError("Solo se permiten formatos JPEG, PNG, JPG o GIF.")
    
                # Redimensiona si excede 800x800 (puedes ajustar)
                max_size = (300, 300)
                if img.height > 300 or img.width > 300:
                    img.thumbnail(max_size)
                    img.save(img_path)
                    
            except ValidationError as e:
                # Borra el archivo subido si hay error
                if os.path.exists(self.imagen.path):
                    os.remove(self.imagen.path)
                raise e
    
    def __str__(self):
        return self.titulo
    

class Calificacion(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE, related_name='calificaciones')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    puntuacion = models.PositiveIntegerField()
    
    class Meta:
        unique_together = ('video', 'usuario')
        
    def __str__(self):
        return f"{self.usuario.username} - {self.video.titulo} - {self.puntuacion}"
    
    

Sroll-VideoApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models import F
from django.db.models import Avg
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseBadRequest
from .models import Video, Categoria, Calificacion
from ConsolaNotificacionesApp.form import ComentarioForm
from ConsolaUsuarioApp.models import Favorito
from ConsolaNotificacionesApp.utils import crear_notificacion
from django.core.paginator import Paginator
from django.db.models import Avg
from ConsolaNotificacionesApp.models import Comentario, Like
import json
from ConsolaImagenApp.models import Imagenes
from itertools import chain
from operator import attrgetter
from django.contrib.contenttypes.models import ContentType
from django.template.loader import render_to_string


def lista_videos_imagenes(request):
    # Ordenar videos según el parámetro en la URL (por defecto "recientes")
    favoritos = []
    
    notificaciones_no_leidas = 0
    ordenar_por = request.GET.get('ordenar', 'recientes')
    
    videos = Video.objects.all()
    imagenes = Imagenes.objects.all()
    
    # Filtrar y ordenar los videos según el parámetro
    if ordenar_por == 'populares':
        videos = videos.order_by('-visualizaciones')  
        #imagenes = imagenes.order_by('-visualizaciones') # Revisar esta palabra clave.
    elif ordenar_por == 'mejor_calificados':
        videos = videos.annotate(promedio_calificaciones=Avg('calificaciones')).order_by('-promedio_calificaciones')
        imagenes = imagenes.annotate(promedio_calificaciones=Avg('calificaciones')).order_by('-promedio_calificaciones')
    else:
        videos = videos.order_by('-fecha_subida')  # Por defecto, recientes
        imagenes = imagenes.order_by('-fecha_subida')
        
    # Obtener categorías para los filtros
    categorias = Categoria.objects.all()
    
    # Filtro por búsqueda y categoría
    query = request.GET.get('q')
    categoria_id = request.GET.get('categoria')
    
    context = {
        'categorias': categorias,
        'ordenar_por': ordenar_por,
        'favoritos': favoritos,
        'notificaciones_no_leidas': notificaciones_no_leidas,
        'categorias_id': categoria_id
    }
    
    return render(request, 'videos/lista_videos_imagenes.html', context)


def cargar_elementos_scroll(request):
    ordenar_por = request.GET.get('ordenar', 'recientes')
    query = request.GET.get('q')
    categoria_id = request.GET.get('categoria')

    # Obtener los videos y las imágenes
    videos = Video.objects.all()
    imagenes = Imagenes.objects.all()

    # Ordenamiento
    if ordenar_por == 'populares':
        videos = videos.order_by('-visualizaciones')
    elif ordenar_por == 'mejor_calificados':
        videos = videos.annotate(promedio_calificaciones=Avg('calificaciones')).order_by('-promedio_calificaciones')
        imagenes = imagenes.annotate(promedio_calificaciones=Avg('calificaciones')).order_by('-promedio_calificaciones')
    else:
        videos = videos.order_by('-fecha_subida')
        imagenes = imagenes.order_by('-fecha_subida')

    # Filtro búsqueda
    if query:
        videos = videos.filter(titulo__icontains=query)
        imagenes = imagenes.filter(titulo__icontains=query)
    
    # Filtro categoría
    if categoria_id and categoria_id.isdigit():
        videos = videos.filter(categorias__id=int(categoria_id))
        imagenes = imagenes.filter(categorias__id=int(categoria_id))

    # Agregar tipo y convertir a listas
    for v in videos:
        v.tipo = 'video'
    for i in imagenes:
        i.tipo = 'imagen'

    videos = list(videos)
    imagenes = list(imagenes)

    elementos = videos + imagenes
    elementos.sort(key=attrgetter('fecha_subida'), reverse=True)

    # Paginación real
    paginador = Paginator(elementos, 15)
    page_num = request.GET.get('page', 1)
    page_obj = paginador.get_page(page_num)

    html = render_to_string('videos/componentes/contenido_grid.html', {
        'page_obj': page_obj,
        'user': request.user
    })

    return JsonResponse({
        'html': html,
        'has_next': page_obj.has_next()
    })    

Sroll-VideoApp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% block extra_styles %}
    {% endblock %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/themes/classic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/pickr.min.js"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Multimedia{% endblock %}</title>
    <!-- Enlace al archivo CSS común -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

{% block custom_styles %}
    {% if request.user.is_authenticated and request.user.perfil %}
        <style>
            :root {
                --perfil-bg: {{ request.user.perfil.color_fondo|default:'rgb(255, 123, 0)' }};
                --perfil-main: {{ request.user.perfil.color_primario|default:'black' }};
                --perfil-text: {{ request.user.perfil.color_texto|default:'black' }};
            }
            
        </style>
    {% endif %}
{% endblock %}

{% if messages %}
    <div class="modal fade" id="mensajeModal" tabindex="-1" aria-labelledby="mensajeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header {% if messages.0.tags == 'success' %}bg-success{% elif messages.0.tags == 'error' %}bg-danger{% else %}bg-primary{% endif %} text-white">
                    <h5 class="modal-title" id="mensajeModalLabel">Mensaje</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Aceptar</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
        var mensajeModal = new bootstrap.Modal(document.getElementById('mensajeModal'));
        mensajeModal.show();
        });
    </script>
{% endif %}


<body class="body">

    <div class="layout-principal">
        {% block zona_fija %}
        <!--Zona fija donde se encuentra navbar y el search-->
        {% endblock %}

        <!-- Zona con scroll infinito -->
        <div class="zona-scrollable" id="zona-scroll">
            <div class="container">
                {% block content %}

                <!-- Aquí va el contenido específico de cada vista -->
                {% endblock %}
            </div>
        </div>

    </div>

    <footer>
        <p style="text-align: center; margin: 15px 0;">&copy; Frenceken 2024</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/interacciones.js' %}"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    
    {% block extra_scripts %}{% endblock %}
</body>
</html>

<script>
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
            cookie = cookie.trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
</script>
{% comment %} <script>
    let page = 1;  // Inicia con la página 1
</script> {% endcomment %}

Sroll-VideoApp/templates/videos/componentes/contenido_grid.html
{% for item in page_obj %}

    {% include 'videos/componentes/item.html' %}
    
{% endfor %}

Sroll-VideoApp/templates/videos/componentes/item.html
{% if item.tipo == 'video' %}
    <div class="video-card">
        {% if user.is_authenticated %}
            <a href="{% url 'ConsolaVideoApp:detalle_video' item.id %}">
                <img src="{{ item.imagen.url }}" alt="{{ item.titulo }}" class="miniatura">
            </a>
            <div class="nombre-superpuesto">{{ item.titulo }}</div>
        {% else %}
            <a href="{% url 'ConsolaUsuarioApp:login' %}?next={% url 'ConsolaVideoApp:detalle_video' item.id %}">
                <img src="{{ item.imagen.url }}" alt="{{ item.titulo }}" class="miniatura">
            </a>
        {% endif %}
    </div>
{% elif item.tipo == 'imagen' %}
    <div class="imagen-card">
        {% if user.is_authenticated %}
            <a href="{% url 'ConsolaImagenApp:detalle_imagen' item.id %}">
                <img src="{{ item.imagen.url }}" alt="{{ item.titulo }}" class="miniatura">
            </a>
            <div class="nombre-superpuesto">{{ item.titulo }}</div>
        {% else %}
            <a href="{% url 'ConsolaUsuarioApp:login' %}?next={% url 'ConsolaImagenApp:detalle_imagen' item.id %}">
                <img src="{{ item.imagen.url }}" alt="{{ item.titulo }}" class="miniatura">
            </a>
        {% endif %}
    </div>
{% endif %}

Sroll-VideoApp/templates/videos/lista_videos_imagenes.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lista de Vídeos{% endblock %}

{% block zona_fija %}
<!-- Zona fija: navbar + cabecera -->
        <nav class="navbar">
            <a href="{% url 'ConsolaVideoApp:lista_videos_imagenes' %}">Inicio</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'Formulario_seleccion_de_carga:seleccionar_tipo_de_archivo' %}">Subir Video / Imagenes</a>
                <div>
                    {% if notificaciones_no_leidas is not None %}
                        <a id="campanaNotificacion"
                            data-url="{% url 'ConsolaNotificacionesApp:cantidad_notificaciones_no_leidas' %}"
                            href="{% url 'ConsolaNotificacionesApp:lista_notificaciones' %}">
                            <i class="fas fa-bell"></i>
                            <span id="contadorNotificaciones">({{ notificaciones_no_leidas }})</span>
                        </a>
                    {% endif %}
                </div>
                <div class="usuario-dropdown">
                    <button type="button" class="usuario-toggle">
                        {{ request.user.username }}
                        {% if request.user.perfil.foto %}
                            <img src="{{ request.user.perfil.foto.url }}" class="avatar-nav">
                        {% else %}
                            <img class="avatar-nav" src="{% static 'img/usuario.png' %}" alt="Foto por defecto">
                        {% endif %}
                        <i class="fas fa-caret-down"></i>
                    </button>
                    <div class="usuario-menu">
                        <form method="POST" action="{% url 'ConsolaPerfiUsuarioApp:perfil_usuario' %}">
                            {% csrf_token %}
                            <button type="submit"> Ver Perfil</button>
                        </form>
                        <form method="POST" action="{% url 'ConsolaUsuarioApp:logout' %}">
                            {% csrf_token %}
                            <button type="submit">Cerrar sesión</button>
                        </form>
                    </div>
                </div>
            {% else %}
                <a href="{% url 'ConsolaUsuarioApp:login' %}">Iniciar sesión</a>
            {% endif %}
        </nav>

        <div class="zona-fija">
            <h1><strong>Comparte tu Foto o Video</strong></h1>
            <div class="search-container">
                <!-- Formulario de búsqueda -->
                <form method="GET" action="{% url 'ConsolaVideoApp:lista_videos_imagenes' %}">
                    <input type="text" name="q" placeholder="Buscar por Nombre..." value="{{ request.GET.q }}">
                    <!-- Filtro por categoría -->
                    <select name="categoria">
                        <option value="">Todas las categorías</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}" {% if request.GET.categoria == categoria.id|stringformat:"s" %}selected{% endif %}>
                                {{ categoria.nombre }}
                            </option>
                        {% endfor %}
                    </select>
                    <button type="submit">Filtrar</button>
                </form>
            </div>
        </div>
{% endblock %}

{% block content %}
<div class="zona-scrollable" id="zona-scroll">
    <div id="contenedor-videos-imagenes" 
        data-url-scroll="{% url 'ConsolaVideoApp:cargar_elementos_scroll' %}" 
        class="video-grid">
        <!--{% include 'videos/componentes/contenido_grid.html' %}-->
    </div>
    <div id="loader" style="text-align:center; display:none;">Cargando más contenido...</div>
</div>

{% endblock %}

<script>
    let page = {{ page_obj.next_page_number|default:2 }};
</script>








{% comment %} <!-- Paginación -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primera</a>
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
        {% endif %}
    </span>
</div> {% endcomment %}


